### ISSUE TITLE
saveAll() with an array of string object Ids instead of objects?

### ISSUE THREAD

**Issue by mindjuice** [neumino/thinky#184] opened 2015-02-22 04:09 UTC
Hi all,

Just started working with Thinky & RethinkDB last week and am really liking it so far!  Very nice work!

I'm working on two models now, Class and User with the following properties:
  * A User can attend multiple Classes
  * A Class can contain multiple Users

I've modelled it with a set of reciprocal **hasAndBelongsToMany** relationships in both directions as below:

    User.hasAndBelongsToMany(Class, 'classesEnrolled', 'id', 'id');
    Class.hasAndBelongsToMany(User, 'students', 'id', 'id');

When I want to put a student User into a class, I build an update JSON object on the client side that looks like this:

    { classesEnrolled: [ '76c4bdc5-d9e5-4b03-98d1-9f39a3ef13db' ],
      id: '7f75a866-0c50-425f-86b5-984b106aebf0' }

I do a **get().getJoin()** on that **id**, and call **doc.merge()** to merge in the **classesEnrolled** array and then call **saveAll()**, but I get the following error:

    TypeError: Object 76c4bdc5-d9e5-4b03-98d1-9f39a3ef13db has no method 'isSaved'

After thinking about this for a while and trying to figure out what was wrong, I looked more closely at your examples and noticed that you only ever show saving a joined document after setting a reference to another joined document.  The error seems to mean that a string object doesn't have an **isSaved()** method (of course it doesn't).

So that's a long-winded way of getting around to asking, is there any way to have Thinky lookup the objects by id string and then establish the relationships for me?  Otherwise, for every object that has these types of relationships, I have to write code to see if one of the joined fields is being saved, asynchronously lookup each of the elements in the array, build up another array with object references instead of strings, and then finally do **saveAll()**.  That would be pretty tedious and error prone.

Thanks.

**Comment by neumino** [comment] 2015-02-22 08:36
Yes, I'm afraid there is currently no way to save a relation with just an id (you need the whole document).

I honestly didn't think about this use case before, and I can easily see how useful and convenient it can be.
I'll try to add this. I believe it shouldn't be not too hard as I just have to save the link and not the document when I find a string/value that is not a document.

Thanks for the feedback!

**Comment by mindjuice** [comment] 2015-02-22 17:45
Cool!  Thanks Michel!  I'm very much looking forward to this improvement.  I'd like to help you improve Thinky as I use it, so let me know if you need some help testing the patch.

Also, not to rush you, but any idea when you might be able to get to this?  I have a few other things I can work on for a while, but if the patch for this will be more than a week or so, I'll probably have to write that nasty async lookup code as I am using relations in quite a few places and every one of them comes from the client UI making an association and sending just the id string of the other doc in a POST or PUT.

Thanks!

**Comment by neumino** [comment] 2015-02-23 02:27
It's currently in the branch `next`.
I have some issues running the tests on wercker, but it should be pushed sometimes today or beginning of next week.

For `belongsTo`/`hasMany`/`hasOne` relations, you can save a relation by using `Model.save(..., {conflict: "update"})`.
For `hasAndBelongsToMany`, you can save the relation by just passing an array of keys instead (like you described in your use case)

**Comment by mindjuice** [comment] 2015-02-23 02:29
That's great!  Thank you!  For the ``hasAndBelongsToMany`` case, does the array I pass in completely replace the old one?  Just want to make sure it's not trying to merge them.

**Comment by neumino** [comment] 2015-02-23 03:04
Yes, instead of passing an array of `Class`, you would just pass an array of the id of the classes.
```
User.hasAndBelongsToMany(Class, 'classesEnrolled', 'id', 'id');
Class.hasAndBelongsToMany(User, 'students', 'id', 'id');


var john = new User(...); // or retrieve from the database
john.classesEnrolled: [ '76c4bdc5-d9e5-4b03-98d1-9f39a3ef13db' ] // 76c4bdc5-d9e5-4b03-98d1-9f39a3ef13db is the id of a class already saved in the database

john.saveAll(classesEnrolled: true}).then(function(result) {
    // The new enrolled class is saved
});
```

**Comment by neumino** [comment] 2015-02-23 03:42
Note about the previous snippet.

You shouldn't retrieve the document with `getJoin({classesEnrolled: true})` and then set the array to a unique value. If you do, you will lose the relations for the document retrieved with `getJoin`.

**Comment by neumino** [comment] 2015-02-23 03:44
It's also released in 1.16.4.
Let me know if you have more questions @mindjuice :)

**Closed by neumino** 2015-02-23 03:44 UTC

**Comment by mindjuice** [comment] 2015-02-23 08:37
This is definitely showing signs of working, but it's not quite right yet.

If I get a ``User`` which has been made a teacher for a given ``School``, the join on the ``School`` works, and the subdocument for the ``School`` also contains the expected ``classes`` array (a ``hasAndBelongsToMany`` join) which has a list of classes associated with the ``School``.  However, if I get the ``School`` directly, the ``classes`` array is not joined in.

I have ``Class``, ``User`` and ``School`` models with some relationships between them.  I've included them below (slightly trimmed down):

    //----------------------------------------------------------------------------------
    // Class Model
    //----------------------------------------------------------------------------------
    var Class = thinky.createModel('Class', {
      id:       type.string().options({enforce_missing: false}),
      name:     type.string(),
      isActive: type.boolean(),
      schoolId: type.string()
    });

    // Referenced models
    var School = require('./school-model.js');
    var User = require('./user-model.js');

    // Relationships
    Class.belongsTo(School, 'school', 'schoolId', 'id');

    Class.hasAndBelongsToMany(User, 'teachers', 'id', 'id');
    Class.hasAndBelongsToMany(User, 'students', 'id', 'id');


    //----------------------------------------------------------------------------------
    // School Model
    //----------------------------------------------------------------------------------
    var School = thinky.createModel('School', {
      id:      type.string().options({enforce_missing: false}),
      name:    type.string(),
      adminId: type.string().options({enforce_missing: false})
    });

    // Referenced models
    var Class = require('./class-model.js');
    var User = require('./user-model.js');

    // Relationships
    School.belongsTo(User, "admin", "adminId", "id");
    School.hasMany(Class, "classes", "id", "schoolId");


    //----------------------------------------------------------------------------------
    // User Model
    //----------------------------------------------------------------------------------
    var User = thinky.createModel('User',{
      id:        type.string().options({enforce_missing: false}),
      firstName: type.string(),
      lastName:  type.string(),
      role:      type.string(),
      schoolId:  type.string(),
      email:     type.string(),

      // Passport fields
      hash:      type.string().options({enforce_missing: false}),
      salt:      type.string().options({enforce_missing: false}),
      last:      type.date().options({enforce_missing: false}),
      attempts:  type.number().options({enforce_missing: false})
    });

    // Referenced models
    var Class = require('./class-model.js');
    var School = require('./school-model.js');

    var Answer = require('./answer-model.js');
    var Element = require('./element-model.js');
    var Mark = require('./mark-model.js');
    var Rating = require('./rating-model.js');
    var Context = require('./context-model.js');

    // Relationships
    User.belongsTo(School, 'school', 'schoolId', 'id');

    User.hasAndBelongsToMany(Class, 'classesTaught',   'id', 'id');
    User.hasAndBelongsToMany(Class, 'classesEnrolled', 'id', 'id');


Here is what I get when requesting the Teachers (slightly edited for space & readability):

    [{"email":"mrs@",
    "firstName":"Mrs",
    "id":"a9af28cd-a3b6-4231-82cb-bd406d2bca40",
    "lastName":"Teacher",
    "role":"teacher",
    "schoolId":"9ccb7a64-c013-47ae-b0e0-d07948be7884"
    "school":{"classes":[{"id":"a3895a71-98e5-4089-bbec-d26a226c4993","isActive":true,"name":"MVHS 101","schoolId":"9ccb7a64-c013-47ae-b0e0-d07948be7884"},{"id":"c125e54d-4d2c-4c9c-872a-4c0f44a26f07","isActive":true,"name":"New Class","schoolId":"9ccb7a64-c013-47ae-b0e0-d07948be7884"}],"id":"9ccb7a64-c013-47ae-b0e0-d07948be7884","isSuspended":false,"name":"Mission High School"}
    }]

Notice that the ``Teacher`` object returned has the ``school`` populated and that ``school`` has ``classes`` populated indicating that both joins were done successfully.

When I ask for the same school directly though, I get just the following:

    {"id":"9ccb7a64-c013-47ae-b0e0-d07948be7884","isSuspended":false,"name":"Mission High School"}

The ``classes`` join is not done.

This is my ``GET`` method (slightly trimmed):

  get: function(req, res, next) {
      var that = this;
      var query;

      // Get all with a query
      var queryObj = this.prepareGetQuery(req, res);

      // Apply the id to the query if given
      if (req.params.id) {
        queryObj.id = req.params.id;
      }

      query = this.model();

      if (Object.keys(queryObj).length) {
        query = query.filter(queryObj);
      }

      // Execute the query
      query.getJoin().run().then(function(data) {
        console.log("returning " + inspect(docs));
        return res.send(docs);
      }).error(function(err) {
        // Error handling
        console.log("get:err=" + inspect(err));
        return res.status(400).end();
      });
    },

So effectively it boils down to:

    User.filter({id: id}).getJoin().run().then()

Any idea what I might be doing wrong?

Thanks!

**Comment by neumino** [comment] 2015-02-24 02:25
You need to do

```
School.filter({id: id}).getJoin({classes: true})
```

This is because you have circular references, and in your case, the query built is this one:

```
School
  -> join admin
    -> join classes
  -> try to join classes, but already performed the joined before, so skip this field
```

From a general point of view, you should use `getJoin({joinToGet: true})` when you have circular references.

**Comment by mindjuice** [comment] 2015-02-26 06:44
Thanks, this is working mostly as expected now, although see #188 for a possibly related issue.

**Comment by primitive-type** [comment] 2015-05-15 22:20
@neumino I have almost this exact use case, but when I do the following:

```
var john = new User(...); // or retrieve from the database
john.classesEnrolled: [ '76c4bdc5-d9e5-4b03-98d1-9f39a3ef13db' ] // 76c4bdc5-d9e5-4b03-98d1-9f39a3ef13db is the id of a class already saved in the database

john.saveAll(classesEnrolled: true}).then(function(result) {
    // The new enrolled class is saved
});
```

I get this error: ```[Error: Cannot build a new instance of `Class` without an object]```

Any ideas as to why that might be?

**Comment by mindjuice** [comment] 2015-05-16 04:30
@primitive-type I think we would need to see your code to be sure.  That code is the example @neumino posted a while back.

It should look something like this (or some variation):

    var classObj = { name: 'English 101', grade: 1 };
    var class = new Class(classObj);

Looking where that error string appears in the thinky code, I would assume that you're not passing a JavaScript object to ``new Class()``.

If that's not it, I can take a closer look if you post your model and your actual code that is creating the object.

**Comment by meznaric** [comment] 2015-06-01 23:48
Can somebody confirm this is working? I am getting same error as @primitive-type. The problem is that thinky tries to create new models for all of the joined documents. But it throws error because new Model `(models.js:127)` expects first parameter to be of type object while we are having just an array of strings for join.

**Comment by sjmueller** [comment] 2015-09-25 04:05
@meznaric, I'm getting the same error both you and @primitive-type are getting.  My exact use case matches his example of a new object with an array of ids for a `hasAndBelongsToMany` relationship.  So I don't think it is working as we expect.

**Comment by neumino** [comment] 2015-09-26 00:39
You should consider this feature deprecated. Please use `addRelation`/`removeRelation` instead.

**Comment by sjmueller** [comment] 2015-09-26 05:23
@neumino, if i'm understanding correctly, are you saying it is no longer possible to link multiple entities to a document by providing an array of ids?  It doesn't seem like `addRelation` supports more than just one joinedDocument as input.

**Comment by neumino** [comment] 2015-09-26 05:35
It's still possible, but if possible people should move from it.
The 3 tests are still passing
https://github.com/neumino/thinky/blob/master/test/advanced.js#L2857

**Comment by neumino** [comment] 2015-09-26 05:37
This feature was basically added before `addRelation`/`removeRelation`. While it works, it brings a few edge cases, and in the end using `addRelation`/removeRelation` does the same, is easier to understand and avoid edge cases.

I'm trying to not introduce backward compatibility between versions (as far as I can), so the functionality still works, but I don't plan to expand it (except if someone brings up a new case that isn't covered by `addRelation`/`removeRelation`)

**Comment by neumino** [comment] 2015-09-26 06:52
@sjmueller -- While the feature is deprecated, I'm happy to help with it if you still have an issue using it. Feel free to open a new bug (with your code).

**Comment by bkniffler** [comment] 2016-07-04 15:56
@neumino 
Automatically handling referenced items like thinky does is such a great and unique feature, its a shame it only really works well if you reference the full items. If you want to link existing objects by IDs you have to go the manual route. 

Why not check if the referenced item is a string and run addRelation internally? This would be much more intuitive and comfortable, especially in scenarios where you auto-generate your UI and your APIs (think of something like a parse.com server where you define models and API is generated).

I can't stress how useful the current feature is compared to other ORMs (sequelize, bookshelf, lookpack, waterline, objectionjs), but its really missing the automatic handling of IDs. You say its due to edge cases that you deprecated the feature. Do these edge cases really out-weight the advantages? You say its easier to understand, but theres already been a few people here expecting IDs to work and getting errors, so maybe it is counter-intuitive?

**Comment by neumino** [comment] 2016-07-05 23:02
@bkniffler -- can you open a new issue since this one is a bit old?
From the top of my head, the problem of doing this is that for a `n-n` relation, we can save a new relation without retrieving the linked document.
So if we want to return a full and valid document, we need to issue one more query.

It's basically work to do :)
