### ISSUE TITLE
Joined documents, pluck and default values

### ISSUE THREAD

**Issue by tomymolina** [neumino/thinky#318] opened 2015-08-14 17:11 UTC
Hi.
I think there is an error when retrieving joined (getJoin) documents (A 'has' B). The error consists in: if you use pluck (inside _apply in getJoin) in B and B has properties with default values in it's schema then all these properties will be plucked in addition to the properties selected in the pluck function.

Example:
**User schema:**
```javascript
var User = thinky.createModel('users', {
    id: type.string(), //do not put here .required()
    firstName: type.string().validator(validateLocalStrategyProperty).default(''),
    lastName: type.string().validator(validateLocalStrategyProperty).default(''),
    displayName: type.string(),
    email: type.string().email().required(),
    username: type.string().required(),
    password: type.string().validator(validateLocalStrategyPassword),
    salt: type.string(),
    provider: type.string(),
    providerData: type.object(),
    additionalProvidersData: type.object(),
    roles: type.array().schema(type.string().enum('user', 'admin')).default(['user']).required(),
    updated: type.date().optional().allowNull(),
    created: type.date().optional().allowNull().default(function(){
        return new Date('01/01/1970');
    }),
    resetPasswordToken: type.string(),
    resetPasswordExpires: type.date()
}, {
    enforce_extra: 'remove'
});
```

**Article model:**
```javascript
var Article = thinky.createModel('articles', {
    created: type.date().optional().default(function(){
        return new Date();
    }),
    title: type.string().required(),
    content: type.string().required(),
    userId: type.string().required(),
    id: type.string() //do not put here .required()
}, {
    enforce_extra : 'remove'
});

Article.belongsTo(User, 'user', 'userId', 'id');
```

And the controller:
```javascript
exports.articleByID = function (req, res, next, id) {
    Article.get(id)
        .getJoin({
            user: {
                _apply : function(user) {
                    return user.pluck('id', 'displayName', 'username');
                }
            }
        })
        .run()
        .then(function (article) {
            if (!article) return next(new Error('Failed to load article ' + id));
            req.article = article;
            next();
        })
        .error(function (err) {
            return next(err);
        });
};
```

When calling the controller it will return the article and the joined document will be:
```javascript
{
    id: 'something',
    displayName: 'something',
    username: 'something',
    firstName: '',
    lastName: '',
    roles: [ 'user' ],
    created: Thu Jan 01 1970 00:00:00 GMT+0100 (CET) 
}
```

The last four attributes should not be returned, right?

**Comment by neumino** [comment] 2015-08-15 00:51
We call the validation when we retrieve an object and since you have default value for these fields, these fields will use their default value.

It's more or less the same issue as in https://github.com/neumino/thinky/issues/186
It's about not running validation when a document is retrieved.

**Comment by neumino** [comment] 2015-08-15 00:51
Closing as duplicate of #186

**Closed by neumino** 2015-08-15 00:51 UTC
