### ISSUE TITLE
Possibility of doing joins across databases. 

### ISSUE THREAD

**Issue by kheide** [neumino/thinky#317] opened 2015-08-13 21:38 UTC
Is there a way to enable doing joins and relations across databases. 

Say I have my Users model in a database called 'core'. And a 'Notifications' model in a database called 'feeds'. Is there a way to join between the two?

**Comment by neumino** [comment] 2015-08-14 03:54
It's not possible at the moment. Thinky uses a unique database.

Closing as duplicate of #227

**Closed by neumino** 2015-08-14 03:54 UTC
