### ISSUE TITLE
Rethinkdbdash and Joi

### ISSUE THREAD

**Issue by Extarys** [neumino/thinky#635] opened 2017-09-20 05:56 UTC
I found a library called nothink that use Joi as the backend to provide the validation/ORM for RethinkDB. I love Joi and I  think it is a very mature and useful library.

Nothink use Rethinkdb driver instead of rethinkdbdash, which I think doesn't offer as much feature as rethinkdbdash.

I don't mean to be rude or to underestimate your work (neumino) or the work of the community around rethinkdb and thinky/rethinkdbdash in any way since I wouldn't be able to achieve 5% of what you did, but - could we make a version of thinky that use Joi as a backend, or simply put, make an ORM that use rethinkdbdash and Joi?

Sorry - I'm always afraid to offense someone when I bring an idea as I'm not as good as you are.

**Comment by grantcarthew** [comment] 2017-09-20 06:22
Hi @Extarys,
This is a duplicate of #277 
Have a read there.
Thanks for your input.

**Closed by grantcarthew** 2017-09-20 06:22 UTC
