### ISSUE TITLE
update in hasAndBelongsToMany docs not working 

### ISSUE THREAD

**Issue by pyadav** [neumino/thinky#281] opened 2015-07-04 16:53 UTC
On update in hasAndBelongsToMany gives some problem.
Possibly unhandled **TypeError: self[key][i]._save** is not a function

**Comment by neumino** [comment] 2015-07-04 16:55
What's the whole stacktrace?

**Comment by pyadav** [comment] 2015-07-04 16:56
Possibly unhandled TypeError: self[key][i]._save is not a function
  at /Users/osfreak/Hubbot/node_modules/thinky/lib/document.js:964:30
  at tryCatch2 (/Users/osfreak/Hubbot/node_modules/thinky/node_modules/bluebird/js/main/util.js:51:21)
  at Promise$_resolveFromResolver [as _resolveFromResolver] (/Users/osfreak/Hubbot/node_modules/thinky/node_modules/bluebird/js/main/promise.js:585:13)
  at new Promise (/Users/osfreak/Hubbot/node_modules/thinky/node_modules/bluebird/js/main/promise.js:82:37)
  at /Users/osfreak/Hubbot/node_modules/thinky/lib/document.js:963:33
  at /Users/osfreak/Hubbot/node_modules/thinky/lib/document.js:976:15
  at Object.loopKeys (/Users/osfreak/Hubbot/node_modules/thinky/lib/util.js:200:16)
  at model.Document._saveMany (/Users/osfreak/Hubbot/node_modules/thinky/lib/document.js:952:8)
  at /Users/osfreak/Hubbot/node_modules/thinky/lib/document.js:841:12
  at Object.tryCatch (/Users/osfreak/Hubbot/node_modules/thinky/lib/util.js:60:5)
  at model.Document._onSaved (/Users/osfreak/Hubbot/node_modules/thinky/lib/document.js:822:8)
  at /Users/osfreak/Hubbot/node_modules/thinky/lib/document.js:788:16
  at tryCatch1 (/Users/osfreak/Hubbot/node_modules/thinky/node_modules/bluebird/js/main/util.js:43:21)
  at Promise$_callHandler [as _callHandler] (/Users/osfreak/Hubbot/node_modules/thinky/node_modules/bluebird/js/main/promise.js:627:13)
  at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/Users/osfreak/Hubbot/node_modules/thinky/node_modules/bluebird/js/main/promise.js:641:18)
  at Promise$_settlePromiseAt [as _settlePromiseAt] (/Users/osfreak/Hubbot/node_modules/thinky/node_modules/bluebird/js/main/promise.js:800:14)
  at Promise$_settlePromises [as _settlePromises] (/Users/osfreak/Hubbot/node_modules/thinky/node_modules/bluebird/js/main/promise.js:934:14)
  at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/Users/osfreak/Hubbot/node_modules/thinky/node_modules/bluebird/js/main/async.js:75:12)
  at Async$consumeFunctionBuffer (/Users/osfreak/Hubbot/node_modules/thinky/node_modules/bluebird/js/main/async.js:38:14)
  at doNTCallback0 (node.js:408:9)
  at process._tickCallback (node.js:337:13)

**Comment by neumino** [comment] 2015-07-04 16:58
A few more questions:
What version of thinky? And what's the model/schema/document involved?

**Comment by pyadav** [comment] 2015-07-04 17:04
thinky version is : 2.0.8

I have two model channel and member which has some relation 
**Channel.hasAndBelongsToMany(Member, 'members', 'id', 'id')**
**Member.hasAndBelongsToMany(Channel, 'channels', 'id', 'id')**

than i am saving member into channel using 
Channel
      .get(channelID)
      .getJoin({members:true})
      .run()
      .then((channel)->
        # new members
        channel.members = "some Object  Array "
        channel.saveAll({members: true},{ conflict: 'replace' })
      ).error(handleError())

**Comment by pyadav** [comment] 2015-07-04 17:48
I make it work -
What i am doing now is first creating  member than saving that id into members. 
this solve my problem but still confuse about **Above error**.

**Comment by neumino** [comment] 2015-07-05 03:14
This seems like a regression to me, I'm pretty sure it was working before.
I'm wrapping a few things with rethinkdbdash 2.1 then I'll look into it.

Thanks for the report @pyadav :)

**Comment by neumino** [comment] 2015-08-09 02:31
Closing as duplicate of #245

**Comment by neumino** [comment] 2015-08-09 22:36
Reopening since it's not a duplicate I think.

**Closed** 2015-08-09 23:29 UTC
Labels: bug

**Comment by neumino** [comment] 2015-08-09 23:31
In 2.0.13
