### ISSUE TITLE
getting a typerror on save with joined documents

### ISSUE THREAD

**Issue by andela-idurotola** [neumino/thinky#392] opened 2015-11-22 05:36 UTC
I get this error when trying to save the modification to the joined documents, so when I try to update only the joins i get this: 
[TypeError: Cannot read property 'new_val' of undefined]
however if the joined documents were untouched the file saves without error

**Comment by neumino** [comment] 2015-11-24 15:59
Closing as duplicate of https://github.com/neumino/thinky/issues/391

**Closed by neumino** 2015-11-24 15:59 UTC
