### ISSUE TITLE
wrap createModel function with common functionality

### ISSUE THREAD

**Issue by almasakchabayev** [neumino/thinky#349] opened 2015-09-18 14:26 UTC
Hello,

I have some common fields for instance id, createdAt, updatedAt and want to follow dry inroder to not repeat all of them in every model.

my attempt was as follows, although not sure how well the code is written, but it shows what I want to achieve:

```
import thinkyConstructor from 'thinky';
import config from '../config';
import {toGlobalId} from 'graphql-relay';

const thinky = thinkyConstructor(config.thinky);
const type = thinky.type;
const r = thinky.r;

const createModel = Object.getPrototypeOf(thinky).createModel;
Object.getPrototypeOf(thinky).createModel = function wrapCreateModel(name, schema, options) {
  console.log(name);
  schema.id = type.string();
  schema.globalId = type.virtual().default(function setRelayGlobalId() {
    return toGlobalId(this.getModel().getTableName(), this.id);
  });
  schema.createdAt = type.date().default(r.now());
  schema.updatedAt = type.date();
  createModel(name, schema, options);
  thinky.models[name].pre('save', function updateEditedField(next) {
    if (this.id) {
      this.updatedAt = new Date();
    }
    next();
  });
};

export default thinky;
```

**Comment by neumino** [comment] 2015-09-18 14:30
Closing as duplicate of https://github.com/neumino/thinky/issues/201

**Closed by neumino** 2015-09-18 14:30 UTC

**Comment by almasakchabayev** [comment] 2015-09-18 14:46
but do you have any suggestions on a workaround for now?

**Comment by neumino** [comment] 2015-09-18 14:53
Your snippet looks fine to me. There's no need for `next` though since your listener is synchronous.

**Comment by almasakchabayev** [comment] 2015-09-18 15:01
I have next as the snippet below does not work as expected, with next it does, shall I make a new issue on this describing the problem?
```
Player.pre('save', function updateEditedField() {
  if (this.id) {
    this.updatedAt = new Date();
  }
});
```

**Comment by almasakchabayev** [comment] 2015-09-18 15:40
So the workaround I ended up with was:

```
import thinkyConstructor from 'thinky';
import config from '../config';
import {toGlobalId} from 'graphql-relay';

const thinky = thinkyConstructor(config.thinky);
const {type, r} = thinky;
const createModel = thinky.createModel;

thinky.createModel = function wrapCreateModel(name, schema, options) {
  schema.id = type.string();
  schema.globalId = type.virtual().default(function setRelayGlobalId() {
    return toGlobalId(this.getModel().getTableName(), this.id);
  });
  schema.createdAt = type.date().default(r.now());
  schema.updatedAt = type.date();
  const model = createModel.call(this, name, schema, options);
  model.pre('save', function updateEditedField(next) {
    if (this.id) {
      this.updatedAt = new Date();
    }
    next();
  });
  return model;
};

export default thinky;
```

Just sharing this for those who stumbled upon this
