### ISSUE TITLE
Multiple dependencies on same model

### ISSUE THREAD

**Issue by gjuchault** [neumino/thinky#290] opened 2015-07-15 10:06 UTC
Hi,

This code do not work :
```js
var thinky = require('thinky')();

var A = thinky.createModel('A', { id : thinky.type.string().optional() });
var B = thinky.createModel('B', { id : thinky.type.string().optional() });
var C = thinky.createModel('C', { id : thinky.type.string().optional() });
var D = thinky.createModel('D', { id : thinky.type.string().optional() });

A.on('ready', function () { console.log('A READY'); });
B.on('ready', function () { console.log('B READY'); });
C.on('ready', function () { console.log('C READY'); });
D.on('ready', function () { console.log('D READY'); });

A.hasMany(B, 'bs', 'id', 'aId'); B.belongsTo(A, 'a', 'aId', 'id');
A.hasMany(C, 'cs', 'id', 'aId'); C.belongsTo(A, 'a', 'aId', 'id');
B.hasMany(D, 'ds', 'id', 'bId'); D.belongsTo(B, 'b', 'bId', 'id');
C.hasMany(D, 'ds', 'id', 'cId'); D.belongsTo(C, 'c', 'cId', 'id');

D.pre('save', function (next) {
    console.log(this);
    next();
});

var a = new A({
    bs: [
        new B({
            ds: [ new D({}) ]
        })
    ],
    cs: [
        new C({
            ds: [ new D({}) ]
        })
    ]
});
a.saveAll().then(r => {
    console.log(require('util').inspect(r, { showHidden: true, depth: 3, colors: true }));
});
```

What I get in console :
```
B READY
A READY
{ bId: '89cd6376-ce52-4f68-af16-01da30838f69' }
D READY
C READY
{ bs: 
   [ { ds: [ [Object], [length]: 1 ],
       aId: 'b619d0cc-e1ce-418f-901d-7e8858972fa1',
       id: '89cd6376-ce52-4f68-af16-01da30838f69' },
     [length]: 1 ],
  cs: 
   [ { ds: [ {}, [length]: 1 ],
       aId: 'b619d0cc-e1ce-418f-901d-7e8858972fa1',
       id: 'eb1c1f0b-2423-4299-9ed7-0e89f88c8162' },
     [length]: 1 ],
  id: 'b619d0cc-e1ce-418f-901d-7e8858972fa1' }
```

So only one `D` is created, and passed to validation.

**Comment by neumino** [comment] 2015-07-15 16:16
Just be explicit with `saveAll` and `getJoin`.
```
a.saveAll({bs : { ds: true}, cs: {ds: true}})
```

Closing as a duplicate of https://github.com/neumino/thinky/issues/274

**Closed by neumino** 2015-07-15 16:16 UTC

**Comment by gjuchault** [comment] 2015-07-15 16:21
The method you gave does indeed fix the issue; but it still should not be that way...
saveAll() and getJoin() should, by default, return the document with **all** the dependencies.
And that is may be easily done by generating the object you give in example with a function that is called if no argument is provided.

**Comment by neumino** [comment] 2015-07-16 07:20
So this is not possible for `getJoin`. For example with this relation:
```
Users.hasAndBelongsToManu(Users, "friends", "id", "id")
```
How many friends should you retrieve?

For `save` we could technically save everything and keep track of references for each document instead of model, but the rule of thumb was if you want to use `save(<param>)`, you should use `getJoin(<param>)`

**Comment by gjuchault** [comment] 2015-07-16 08:15
Fair enough.
